id: A02F2058E
title: A Sādhana of Jambhala
type: translation
pechas:
- I6A79944E
- I467F3203
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:25.620653
  last_modified_at: 2023-01-04 13:11:25.620661
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I6A79944E/AF26: 9F46
  I467F3203/85DE: 9F46
